require: 'rubocop-rails'

Rails:
  Enabled: true
AllCops:
  Exclude:
    - bin/*
    - config/application.rb
    - config/environments/*
    - config/initializers/*
    - db/schema.rb
    - db/migrate/*
    - log/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
Layout/AbcSize:
  Max: 30
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
  EnforcedStyle: context_dependent
Style/TrailingWhitespace:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
